#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Acme\NewCommand;
use Symfony\Component\Console\Application;


$application = new Application("Laracast demo", "1.1");

// ... register commands
$application->add(new NewCommand(new GuzzleHttp\Client));
$application->run();


